//---------------------------------------------------------------------------
#ifndef mainH
#define mainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
#include <ToolWin.hpp>
#include <ImgList.hpp>
#include "ds_nls.hpp"
#include "inifiles.hpp"
#include <Menus.hpp>
#include <ActnList.hpp>
#include <Dialogs.hpp>
#include <FileCtrl.hpp>
#include "Plusmemo.hpp"
#include "LsFileExplorer28.hpp"
#include "ExtHilit.hpp"
#include <Buttons.hpp>
#include "HTTPGet.hpp"
#include "pmprint.hpp"
#include <ExtDlgs.hpp>
#include "SHDocVw_OCX.h"
#include <OleCtrls.hpp>
#include <Grids.hpp>
#include "FtpListView.hpp"
#include "Ftp.hpp"
#include "FTPSock.hpp"
#include "jpeg.hpp"
#include "enpnggr.hpp"
#include "u_TopStyleIntegration.hpp"
#include "PMSupport.hpp"

//---------------------------------------------------------------------------
class THauptformular : public TForm
{
__published:	// Von der IDE verwaltete Komponenten
        TControlBar *ControlBar1;
        TPageControl *KomponentenLeiste;
        TTabSheet *TabSheet1;
        TTabSheet *TabSheet2;
        TTabSheet *TabSheet3;
        TToolBar *DateiOpLeiste;
        TToolButton *ToolButton1;
        TToolButton *ToolButton2;
        TToolButton *ToolButton3;
        TToolButton *ToolButton4;
        TToolBar *MenuLeiste;
        TToolButton *ToolButton5;
        TToolButton *ToolButton6;
        TToolButton *ToolButton7;
        TToolButton *ToolButton8;
        TToolButton *ToolButton9;
        TToolButton *ToolButton10;
        TToolButton *ToolButton11;
        TImageList *AktiveGrafiken;
        TTabSheet *TabSheet4;
        TTabSheet *TabSheet5;
        TToolBar *BearbeitenOpLeiste;
        TToolButton *ToolButton12;
        TToolButton *ToolButton13;
        TToolButton *ToolButton14;
        TToolButton *ToolButton15;
        TToolButton *ToolButton16;
        TToolButton *ToolButton17;
        TToolButton *ToolButton18;
        TToolButton *ToolButton19;
        TToolButton *ToolButton20;
        TToolButton *ToolButton21;
        TToolButton *ToolButton22;
        TToolBar *BrowserLeiste;
        TToolButton *ToolButton23;
        TToolBar *AndereLeiste;
        TToolButton *ToolButton24;
        TToolButton *ToolButton25;
        TImageList *InaktiveGrafiken;
        TPopupMenu *SeiteMenu;
        TPopupMenu *BearbeitenMenu;
        TPopupMenu *AnsichtMenu;
        TPopupMenu *EinfgenMenu;
        TPopupMenu *FormatMenu;
        TPopupMenu *ToolsMenu;
        TPopupMenu *HilfeMenu;
        TPopupMenu *BrowserMenu;
        TMenuItem *Neu1;
        TMenuItem *NeuesProjekt1;
        TMenuItem *N1;
        TMenuItem *ffnen1;
        TMenuItem *ffnenausdemInternet1;
        TMenuItem *N2;
        TMenuItem *Speichern1;
        TMenuItem *N3;
        TMenuItem *Speichernunter1;
        TMenuItem *SpeichernalsVorlage1;
        TMenuItem *Allespeichern1;
        TMenuItem *Schlieen1;
        TMenuItem *Alleschlieen1;
        TMenuItem *N5;
        TMenuItem *Drucken1;
        TMenuItem *Druckereinrichten1;
        TMenuItem *N6;
        TMenuItem *Beenden1;
        TMenuItem *Rckgngig1;
        TMenuItem *Widerrufen1;
        TMenuItem *N7;
        TMenuItem *Ausschneiden1;
        TMenuItem *Kopieren1;
        TMenuItem *Einfgen1;
        TMenuItem *Lschen1;
        TMenuItem *N8;
        TMenuItem *Allesmarkieren1;
        TMenuItem *N9;
        TMenuItem *Suchen1;
        TMenuItem *Weitersuchen1;
        TMenuItem *Ersetzen1;
        TMenuItem *N10;
        TMenuItem *GehezuZeile1;
        TMenuItem *N11;
        TMenuItem *Einrcken1;
        TMenuItem *Ausrcken1;
        TActionList *ShortCutDummy;
        TPrinterSetupDialog *DruckerSetup;
        TPanel *VerwaltungsPaneel;
        TPlusMemo *TempMemo;
        TFileListBox *TempDateilistBox;
        TStatusBar *StatusLeiste;
        TSplitter *Splitter1;
        TPageControl *VerwControl;
        TTabSheet *VerwTab1;
        TTabSheet *VerwTab2;
        TTabSheet *VerwTab4;
        TTabSheet *VerwTab5;
        TPanel *SonderZeichenPaneel;
        TTabControl *FensterLeiste;
        TToolButton *ToolButton26;
        TPopupMenu *FensterMenu;
        TMenuItem *Nebeneinander1;
        TMenuItem *berlappend1;
        TMenuItem *Symboleanordnen1;
        TMenuItem *Untereinander1;
        TListBox *MDIKinderTitel;
        TLsDirTree21 *DateimanagerExplorer;
        TSplitter *Splitter2;
        TListView *DateimanagerListe;
        TExtHighlighter *TextfeldHighlighter;
        TLsFilelistView28 *DateimanagerTemp;
        TPanel *Panel1;
        TLabel *Label1;
        TPanel *Panel3;
        TSpeedButton *SpeedButton1;
        TAction *NeuShortCut;
        TOpenDialog *OeffnenDialog;
        TAction *OeffnenShortCut;
        THTTPGet *HTTPClient;
        TdsNLS *SprachenWaehler;
        TMenuItem *Browser11;
        TMenuItem *Browser21;
        TMenuItem *Browser31;
        TImageList *GrosseGrafiken;
        TPanel *Panel4;
        TComboBox *ProjekteAuswahl;
        TTreeView *ProjekteExplorer;
        TSplitter *Splitter3;
        TListView *ProjekteListe;
        TToolBar *ToolBar1;
        TToolButton *ToolButton27;
        TFileListBox *ProjekteOrdner1;
        TFileListBox *ProjekteOrdner2;
        TToolButton *ToolButton28;
        TLsFilelistView28 *ProjektmanagerTemp;
        TMenuItem *Info1;
        TListBox *AddLangStuff;
        TSaveDialog *SpeichernunterDialog;
        TTabSheet *VerwTab3;
        TLabel *DirektFTPLabel;
        TPlusMemoPrinter *TextfeldDrucker;
        TAction *SpeichernShortCut;
        TAction *DruckenShortCut;
        TAction *RueckgaengigShortCut;
        TAction *WiderrufenShortCut;
        TAction *AusschneidenShortCut;
        TAction *KopierenShortCut;
        TAction *EinfuegenShortCut;
        TAction *AllesmarkierenShortCut;
        TAction *WeitersuchenShortCut;
        TAction *EinrueckenShortCut;
        TAction *AusrueckenShortCut;
        TReplaceDialog *ErsetzenEinzel;
        TFindDialog *SuchenEinzel;
        TMenuItem *ErweitertesSuchenundErsetzen1;
        TTabSheet *TabSheet7;
        TTabControl *ButtonxControl;
        TPopupMenu *DateimanagerListeMenu;
        TPopupMenu *ProjekteListeMenu;
        TPopupMenu *ProjekteExplorerMenu;
        TMenuItem *ffnen2;
        TMenuItem *Ausfhren1;
        TMenuItem *N4;
        TMenuItem *Neu2;
        TMenuItem *N12;
        TMenuItem *Kopieren2;
        TMenuItem *Einfgen2;
        TMenuItem *N13;
        TMenuItem *Lschen2;
        TMenuItem *Umbenennen1;
        TMenuItem *N14;
        TMenuItem *Filter1;
        TMenuItem *Aktualisieren1;
        TMenuItem *N15;
        TMenuItem *Eigenschaften1;
        TMenuItem *AlleDateien1;
        TMenuItem *N16;
        TMenuItem *Dokumente1;
        TMenuItem *Grafiken1;
        TListBox *TempDateiOperationenKopieren;
        TMenuItem *Andere1;
        TListBox *TempDateiOperationenLoeschen;
        TMenuItem *StandardDokument1;
        TMenuItem *N17;
        TMenuItem *AddLangNewDocLeer11;
        TMenuItem *AddLangNewDocLeer13;
        TMenuItem *AddLangNewDocLeer12;
        TMenuItem *NeuerOrdner1;
        TMenuItem *N18;
        TMenuItem *Lschen3;
        TMenuItem *Umbenennen2;
        TMenuItem *N19;
        TMenuItem *Aktualisieren2;
        TMenuItem *ffnen3;
        TMenuItem *Ausfhren2;
        TMenuItem *N20;
        TMenuItem *Neu3;
        TMenuItem *StandardDokument2;
        TMenuItem *N21;
        TMenuItem *N22;
        TMenuItem *Kopieren3;
        TMenuItem *Einfgen3;
        TMenuItem *N23;
        TMenuItem *Lschen4;
        TMenuItem *Umbenennen3;
        TMenuItem *N24;
        TMenuItem *Filter2;
        TMenuItem *Aktualisieren3;
        TMenuItem *N25;
        TMenuItem *Eigenschaften2;
        TMenuItem *AlleDateien2;
        TMenuItem *N26;
        TMenuItem *Dokumente2;
        TMenuItem *Grafiken2;
        TMenuItem *Andere2;
        TMenuItem *AddLangNewDocLeer21;
        TMenuItem *AddLangNewDocLeer22;
        TMenuItem *AddLangNewDocLeer23;
        TPanel *FarbauswahlPaneel;
        TScrollBox *ScrollBox1;
        TImage *FarbPaletteBild;
        TPanel *Panel5;
        TEdit *FarbPaletteEdit;
        TShape *FarbPaletteShape;
        TLabel *AktuelleFarbeinPalette;
        TToolBar *ToolBar2;
        TToolButton *ToolButton29;
        TListBox *ColorColorNames;
        TListBox *ColorXHTMLCodes;
        TOpenPictureDialog *PaletteOeffnenDialog;
        TColorDialog *GemeinsamerFarbDialog;
        TToolBar *ToolBar3;
        TToolButton *ToolButton30;
        TStringGrid *SonderZeichenGrid;
        TListBox *SonderzeichenCodes;
        TListBox *SonderzeichenNames;
        TListBox *SonderzeichenDescs;
        TMenuItem *InternerBrowser1;
        TMenuItem *N27;
        TMenuItem *ExternerBrowser11;
        TMenuItem *ExternerBrowser21;
        TMenuItem *ExternerBrowser31;
        TMenuItem *N28;
        TMenuItem *Verwaltung1;
        TMenuItem *Statusleiste1;
        TMenuItem *Zeilennummerierung1;
        TMenuItem *N29;
        TMenuItem *Dokumenteinfrbungaktualisieren1;
        TMenuItem *N30;
        TMenuItem *Zeilenumbruch1;
        TMenuItem *Browserintern;
        TMenuItem *N31;
        TAction *AnsichtInternerBrowserShortCut;
        TAction *AnsichtExternerBrowserShortCut1;
        TAction *AnsichtExternerBrowserShortCut2;
        TAction *AnsichtExternerBrowserShortCut3;
        TAction *VerwaltungShortCut;
        TAction *ZeilenumbruchShortCut;
        TPanel *Panel2;
        TComboBox *DirektFTPAuswahl;
        TToolBar *ToolBar4;
        TToolButton *ToolButton31;
        TToolButton *ToolButton32;
        TListView *DirektFTPExplorer;
        TSplitter *Splitter4;
        TListView *DirektFTPListe;
        TPopupMenu *DirektFTPExplorerMenu;
        TMenuItem *NeuerOrdner2;
        TMenuItem *N32;
        TMenuItem *Lschen5;
        TMenuItem *Umbenennen4;
        TMenuItem *N33;
        TMenuItem *Aktualisieren4;
        TPopupMenu *DirektFTPListeMenu;
        TMFtpListView *DirektFTPTemp;
        TMFtp *DirektFTPClient;
        TMenuItem *ffnen4;
        TMenuItem *N34;
        TMenuItem *Neu4;
        TMenuItem *N35;
        TMenuItem *Kopieren4;
        TMenuItem *Einfgen4;
        TMenuItem *N36;
        TMenuItem *Lschen6;
        TMenuItem *Umbenennen5;
        TMenuItem *N37;
        TMenuItem *Filter3;
        TMenuItem *Aktualisieren5;
        TMenuItem *AlleDateien3;
        TMenuItem *N38;
        TMenuItem *Dokumente3;
        TMenuItem *Grafiken3;
        TMenuItem *Andere3;
        TMenuItem *StandardDokument3;
        TMenuItem *N39;
        TMenuItem *AddLangNewDocLeer31;
        TMenuItem *AddLangNewDocLeer32;
        TMenuItem *AddLangNewDocLeer33;
        TProgressBar *DirektFTPStatus;
        TToolButton *ToolButton33;
        TToolButton *ToolButton34;
        TPopupMenu *QuickstartMenu;
        TMenuItem *QuickstartApp1;
        TMenuItem *QuickstartApp2;
        TMenuItem *QuickstartApp3;
        TMenuItem *QuickstartApp4;
        TMenuItem *QuickstartApp5;
        TMenuItem *N40;
        TMenuItem *NeueVerknpfung1;
        TListBox *TempDateiOperationenKopierenExplorer;
        TMenuItem *Schrift1;
        TMenuItem *N41;
        TMenuItem *Paragraph1;
        TMenuItem *Abschnitt1;
        TMenuItem *N42;
        TMenuItem *berschrift1;
        TMenuItem *Gre11;
        TMenuItem *Gre21;
        TMenuItem *Gre31;
        TMenuItem *Gre41;
        TMenuItem *Gre51;
        TMenuItem *Gre61;
        TMenuItem *N43;
        TMenuItem *Fett1;
        TMenuItem *Kursiv1;
        TMenuItem *AndereFormatierungen1;
        TMenuItem *N44;
        TMenuItem *Liste1;
        TMenuItem *Listeneintrag1;
        TMenuItem *N45;
        TMenuItem *Definitionsliste1;
        TMenuItem *Definitionsabschnitt1;
        TMenuItem *Definitionseintrag1;
        TMenuItem *Hochgestellt1;
        TMenuItem *Tiefgestellt1;
        TMenuItem *N47;
        TMenuItem *Prformatiert1;
        TMenuItem *Emphatisch1;
        TMenuItem *N48;
        TMenuItem *Zitat1;
        TMenuItem *Adresse1;
        TMenuItem *N49;
        TMenuItem *Gro1;
        TMenuItem *Klein1;
        TMenuItem *Code1;
        TMenuItem *Schnellformatierung1;
        TMenuItem *N50;
        TAction *FettSchriftShortCut;
        TAction *KursivSchriftShortCut;
        TMenuItem *Hyperlink1;
        TMenuItem *Anker1;
        TMenuItem *eMailVerweis1;
        TMenuItem *N46;
        TMenuItem *Grafik1;
        TMenuItem *Trennlinie1;
        TMenuItem *MultimediaObjekt1;
        TMenuItem *Metatag1;
        TMenuItem *N51;
        TMenuItem *Tabellen1;
        TMenuItem *Formular1;
        TMenuItem *Frames1;
        TMenuItem *N52;
        TMenuItem *CascadingStyleSheets1;
        TAction *AbschnittShortCut;
        TMenuItem *JavaScript1;
        TAction *HyperlinkShortCut;
        TAction *MetatagShortCut;
        TAction *GrafikShortCut;
        TAction *EMailShortCut;
        TMenuItem *httpscribede1;
        TMenuItem *N53;
        TSaveDialog *DirectoryWrongPathDialog;
        TImage *TempGrafik;
        TMenuItem *StyleSheetEditor1;
        TMenuItem *N54;
        TMenuItem *XHTMLKonverter1;
        TMenuItem *N55;
        TMenuItem *Linkberprfung1;
        TMenuItem *Downloadzeit1;
        TMenuItem *N56;
        TMenuItem *Buttonx1;
        TMenuItem *Plugins1;
        TMenuItem *FastCode1;
        TMenuItem *N57;
        TMenuItem *ProjektBackup1;
        TMenuItem *ThumbnailGenerator1;
        TMenuItem *GrafikKatalog1;
        TMenuItem *N58;
        TMenuItem *Optionen1;
        TMenuItem *Includesaktualisieren1;
        TMenuItem *TabellenAssistent1;
        TMenuItem *N59;
        TMenuItem *Tabelle2;
        TMenuItem *Zeile1;
        TMenuItem *Kopfzelle1;
        TMenuItem *Zelle1;
        TMenuItem *N60;
        TMenuItem *berUnterschrift1;
        TAction *TabellenAssistentShortCut;
        TMenuItem *Formular2;
        TMenuItem *N61;
        TMenuItem *Eingabefeld1;
        TMenuItem *Textfeld1;
        TMenuItem *AbsendenundZurcksetzenbutton1;
        TMenuItem *Passwortfeld1;
        TMenuItem *VerstecktesFeld1;
        TMenuItem *N62;
        TMenuItem *Checkbox1;
        TMenuItem *Radiobutton1;
        TMenuItem *N63;
        TMenuItem *Auswahlliste1;
        TMenuItem *Auswahleintrag1;
        TMenuItem *N64;
        TMenuItem *Button1;
        TMenuItem *FramesAssistent1;
        TMenuItem *N65;
        TMenuItem *FrameBereich1;
        TMenuItem *Frame1;
        TMenuItem *N66;
        TMenuItem *EingebettetesFrame1;
        TAction *FrameAssistentShortCut;
        TMenuItem *StyleSheetDefinition1;
        TMenuItem *StyleSheetZuweisungen1;
        TMenuItem *N67;
        TMenuItem *ExterneStyleSheetDatei1;
        TMenuItem *JavaScriptVorlagen1;
        TMenuItem *N68;
        TMenuItem *JavaScript2;
        TMenuItem *ExterneJavaScriptDatei1;
        TAction *JavaScriptDefinitionShortCut;
        TMenuItem *N69;
        TMenuItem *IncludeDatei1;
        TToolBar *ToolbarAllgemein;
        TToolButton *ToolButton35;
        TToolButton *ToolButton36;
        TToolButton *ToolButton37;
        TToolButton *ToolButton38;
        TToolButton *ToolButton39;
        TToolButton *ToolButton40;
        TToolButton *ToolButton41;
        TToolButton *ToolButton42;
        TToolButton *ToolButton43;
        TToolButton *ToolButton44;
        TToolButton *ToolButton45;
        TToolButton *ToolButton46;
        TToolButton *ToolButton47;
        TToolBar *ToolBarZusaetzlich;
        TToolButton *ToolButton48;
        TToolButton *ToolButton49;
        TToolButton *ToolButton50;
        TListBox *AutoComplete;
        TMenuItem *Seiteneigenschaften1;
        TMenuItem *N70;
        TMenuItem *Zeilenumbruch2;
        TPlusMemo *TempMemo2;
        TToolBar *ToolBarFormat;
        TToolBar *ToolBarTabellen;
        TToolButton *ToolButton51;
        TToolButton *ToolButton52;
        TToolButton *ToolButton53;
        TToolButton *ToolButton54;
        TToolButton *ToolButton55;
        TToolButton *ToolButton56;
        TToolButton *ToolButton57;
        TToolButton *ToolButton58;
        TToolButton *ToolButton59;
        TToolButton *ToolButton60;
        TToolButton *ToolButton61;
        TToolButton *ToolButton62;
        TToolButton *ToolButton63;
        TToolButton *ToolButton64;
        TToolButton *ToolButton65;
        TToolButton *ToolButton66;
        TToolButton *ToolButton67;
        TToolButton *ToolButton68;
        TToolButton *ToolButton69;
        TToolButton *ToolButton70;
        TToolButton *ToolButton71;
        TToolButton *ToolButton72;
        TToolButton *ToolButton73;
        TToolButton *ToolButton74;
        TToolButton *ToolButton75;
        TToolButton *ToolButton76;
        TToolButton *ToolButton77;
        TMenuItem *Linksbndig1;
        TMenuItem *Zentriert1;
        TMenuItem *Rechtsbndig1;
        TMenuItem *Blocksatz1;
        TListBox *MySQLSyntax;
        TListBox *PHPKeywordsSyntax;
        TListBox *JavaScriptSyntax;
        TListBox *TabellenSyntax;
        TPlusMemo *TempMemo3;
        TAction *RueckgaengigShortCut2;
        TPopupMenu *DateimanagerExplorerMenu;
        TMenuItem *MenuItem23;
        TToolBar *ToolBarFormulare;
        TToolButton *ToolButton78;
        TToolButton *ToolButton79;
        TToolButton *ToolButton80;
        TToolButton *ToolButton81;
        TToolButton *ToolButton82;
        TToolButton *ToolButton83;
        TToolButton *ToolButton84;
        TToolButton *ToolButton85;
        TToolButton *ToolButton86;
        TToolButton *ToolButton87;
        TToolButton *ToolButton88;
        TToolButton *ToolButton89;
        TToolButton *ToolButton90;
        TToolButton *ToolButton91;
        TToolButton *ToolButton92;
        TAction *LeerzeichenShortCut;
        TAction *ZeilenumbruchShortCut2;
        TAction *KlammerAufShortCut;
        TAction *KlammerZuShortCut;
        TAction *AnfuehrungszeichenShortCut;
        TToolButton *ToolButton93;
        TToolButton *ToolButton94;
        TToolButton *ToolButton95;
        TToolButton *ToolButton96;
        TToolButton *ToolButton97;
        TToolButton *ToolButton98;
        TToolButton *ToolButton99;
        TToolButton *ToolButton100;
        TToolButton *ToolButton101;
        TListBox *SonderzeichenNamesLite;
        TListBox *SonderzeichenCodesLite;
        TMenuItem *Hilfethemen1;
        TMenuItem *N71;
        TMenuItem *Editor1;
        TMenuItem *XHTML1;
        TMenuItem *N72;
        TMenuItem *N74;
        TMenuItem *Upload2;
        TMenuItem *AsciiModus1;
        TMenuItem *BinrModus1;
        TMenuItem *N75;
        TMenuItem *Upload3;
        TMenuItem *AsciiModus2;
        TMenuItem *BinrModus2;
        TListBox *TempDateiOperationenKopieren2;
        TAction *ParagraphShortCut;
        TMenuItem *N73;
        TMenuItem *Eigenschaften3;
        TPanel *Panel6;
        TShape *FarbCursorShape;
        TToolBar *ToolBar5;
        TToolButton *ToolButton102;
        TLabel *AktuelleFarbebeiCursor;
        TAction *PassendeKlammerShortCut;
        TMenuItem *N76;
        TMenuItem *PassendeKlammerfinden1;
        void __fastcall FormShow(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall Beenden1Click(TObject *Sender);
        void __fastcall Druckereinrichten1Click(TObject *Sender);
        void __fastcall berlappend1Click(TObject *Sender);
        void __fastcall Symboleanordnen1Click(TObject *Sender);
        void __fastcall Nebeneinander1Click(TObject *Sender);
        void __fastcall Untereinander1Click(TObject *Sender);
        void __fastcall FensterLeisteChange(TObject *Sender);
        void __fastcall DateimanagerExplorerDirChange(TObject *Sender,
          AnsiString SelectedPath);
        void __fastcall DateimanagerListeClick(TObject *Sender);
        void __fastcall ffnen1Click(TObject *Sender);
        void __fastcall Neu1Click(TObject *Sender);
        void __fastcall ffnenausdemInternet1Click(TObject *Sender);
        void __fastcall HTTPClientDoneFile(TObject *Sender,
          AnsiString FileName, int FileSize);
        void __fastcall BrowserMenuPopup(TObject *Sender);
        void __fastcall Schlieen1Click(TObject *Sender);
        void __fastcall SeiteMenuPopup(TObject *Sender);
        void __fastcall ProjekteListeClick(TObject *Sender);
        void __fastcall NeuesProjekt1Click(TObject *Sender);
        void __fastcall ProjekteAuswahlChange(TObject *Sender);
        void __fastcall ProjekteExplorerChange(TObject *Sender,
          TTreeNode *Node);
        void __fastcall ProjekteExplorerExpanding(TObject *Sender,
          TTreeNode *Node, bool &AllowExpansion);
        void __fastcall Info1Click(TObject *Sender);
        void __fastcall Speichern1Click(TObject *Sender);
        void __fastcall Speichernunter1Click(TObject *Sender);
        void __fastcall Alleschlieen1Click(TObject *Sender);
        void __fastcall Allespeichern1Click(TObject *Sender);
        void __fastcall SpeichernalsVorlage1Click(TObject *Sender);
        void __fastcall Drucken1Click(TObject *Sender);
        void __fastcall BearbeitenMenuPopup(TObject *Sender);
        void __fastcall Rckgngig1Click(TObject *Sender);
        void __fastcall Widerrufen1Click(TObject *Sender);
        void __fastcall Ausschneiden1Click(TObject *Sender);
        void __fastcall Kopieren1Click(TObject *Sender);
        void __fastcall Einfgen1Click(TObject *Sender);
        void __fastcall Lschen1Click(TObject *Sender);
        void __fastcall Allesmarkieren1Click(TObject *Sender);
        void __fastcall Suchen1Click(TObject *Sender);
        void __fastcall Einrcken1Click(TObject *Sender);
        void __fastcall Ausrcken1Click(TObject *Sender);
        void __fastcall GehezuZeile1Click(TObject *Sender);
        void __fastcall SuchenEinzelFind(TObject *Sender);
        void __fastcall ErweitertesSuchenundErsetzen1Click(
          TObject *Sender);
        void __fastcall Ersetzen1Click(TObject *Sender);
        void __fastcall ErsetzenEinzelFind(TObject *Sender);
        void __fastcall ErsetzenEinzelReplace(TObject *Sender);
        void __fastcall Neu2Click(TObject *Sender);
        void __fastcall ffnen2Click(TObject *Sender);
        void __fastcall Ausfhren1Click(TObject *Sender);
        void __fastcall DateimanagerListeMenuPopup(TObject *Sender);
        void __fastcall Kopieren2Click(TObject *Sender);
        void __fastcall Einfgen2Click(TObject *Sender);
        void __fastcall Aktualisieren1Click(TObject *Sender);
        void __fastcall Lschen2Click(TObject *Sender);
        void __fastcall Umbenennen1Click(TObject *Sender);
        void __fastcall DateimanagerListeEdited(TObject *Sender,
          TListItem *Item, AnsiString &S);
        void __fastcall Eigenschaften1Click(TObject *Sender);
        void __fastcall AlleDateien1Click(TObject *Sender);
        void __fastcall Dokumente1Click(TObject *Sender);
        void __fastcall Grafiken1Click(TObject *Sender);
        void __fastcall Andere1Click(TObject *Sender);
        void __fastcall StandardDokumentClick(TObject *Sender);
        void __fastcall ToolButton1Click(TObject *Sender);
        void __fastcall AddLangNewDocLeer1Click(TObject *Sender);
        void __fastcall AddLangNewDocLeer2Click(TObject *Sender);
        void __fastcall AddLangNewDocLeer3Click(TObject *Sender);
        void __fastcall ProjekteExplorerMenuPopup(TObject *Sender);
        void __fastcall Umbenennen2Click(TObject *Sender);
        void __fastcall ProjekteExplorerEdited(TObject *Sender,
          TTreeNode *Node, AnsiString &S);
        void __fastcall Aktualisieren2Click(TObject *Sender);
        void __fastcall Lschen3Click(TObject *Sender);
        void __fastcall ToolButton28Click(TObject *Sender);
        void __fastcall NeuerOrdner1Click(TObject *Sender);
        void __fastcall ProjekteListeMenuPopup(TObject *Sender);
        void __fastcall ffnen3Click(TObject *Sender);
        void __fastcall Ausfhren2Click(TObject *Sender);
        void __fastcall Kopieren3Click(TObject *Sender);
        void __fastcall Einfgen3Click(TObject *Sender);
        void __fastcall Lschen4Click(TObject *Sender);
        void __fastcall Umbenennen3Click(TObject *Sender);
        void __fastcall ProjekteListeEdited(TObject *Sender,
          TListItem *Item, AnsiString &S);
        void __fastcall Aktualisieren3Click(TObject *Sender);
        void __fastcall Eigenschaften2Click(TObject *Sender);
        void __fastcall AlleDateien2Click(TObject *Sender);
        void __fastcall Dokumente2Click(TObject *Sender);
        void __fastcall Grafiken2Click(TObject *Sender);
        void __fastcall Andere2Click(TObject *Sender);
        void __fastcall Neu3Click(TObject *Sender);
        void __fastcall FarbPaletteBildMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall FarbPaletteBildClick(TObject *Sender);
        void __fastcall ToolButton29Click(TObject *Sender);
        void __fastcall ToolButton30Click(TObject *Sender);
        void __fastcall SonderZeichenPaneelResize(TObject *Sender);
        void __fastcall ScrollBox1Resize(TObject *Sender);
        void __fastcall VerwControlChange(TObject *Sender);
        void __fastcall SonderZeichenGridMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall SonderZeichenGridClick(TObject *Sender);
        void __fastcall AnsichtMenuPopup(TObject *Sender);
        void __fastcall InternerBrowser1Click(TObject *Sender);
        void __fastcall ExternerBrowser11Click(TObject *Sender);
        void __fastcall ExternerBrowser21Click(TObject *Sender);
        void __fastcall ExternerBrowser31Click(TObject *Sender);
        void __fastcall Verwaltung1Click(TObject *Sender);
        void __fastcall Statusleiste1Click(TObject *Sender);
        void __fastcall Zeilennummerierung1Click(TObject *Sender);
        void __fastcall Dokumenteinfrbungaktualisieren1Click(
          TObject *Sender);
        void __fastcall Zeilenumbruch1Click(TObject *Sender);
        void __fastcall DirektFTPAuswahlChange(TObject *Sender);
        void __fastcall NeuerOrdner2Click(TObject *Sender);
        void __fastcall Lschen5Click(TObject *Sender);
        void __fastcall Umbenennen4Click(TObject *Sender);
        void __fastcall DirektFTPAktualisieren(TObject *Sender);
        void __fastcall ToolButton31Click(TObject *Sender);
        void __fastcall DirektFTPExplorerMenuPopup(TObject *Sender);
        void __fastcall DirektFTPListeMenuPopup(TObject *Sender);
        void __fastcall DirektFTPClientFtpQuit(TObject *Sender);
        void __fastcall ToolButton32Click(TObject *Sender);
        void __fastcall DirektFTPClientLoggedIn(TObject *Sender);
        void __fastcall DirektFTPClientFtpInfo(TObject *Sender,
          FtpInfo info, AnsiString addinfo);
        void __fastcall DirektFTPClientFtpReady(TObject *Sender);
        void __fastcall DirektFTPClientFtpBusy(TObject *Sender);
        void __fastcall DirektFTPClientFtpError(TObject *Sender,
          FtpError error, AnsiString addinfo);
        void __fastcall DirektFTPClientFileTransferred(TObject *Sender);
        void __fastcall DirektFTPClientAborted(TObject *Sender);
        void __fastcall DirektFTPClientDirectoryChanged(TObject *Sender);
        void __fastcall DirektFTPClientDirectoryCreated(TObject *Sender);
        void __fastcall DirektFTPClientDirectoryDeleted(TObject *Sender);
        void __fastcall DirektFTPClientFileDeleted(TObject *Sender);
        void __fastcall DirektFTPClientFileReceived(TObject *Sender);
        void __fastcall DirektFTPClientFileRenamed(TObject *Sender);
        void __fastcall ffnen4Click(TObject *Sender);
        void __fastcall Kopieren4Click(TObject *Sender);
        void __fastcall Einfgen4Click(TObject *Sender);
        void __fastcall Lschen6Click(TObject *Sender);
        void __fastcall Umbenennen5Click(TObject *Sender);
        void __fastcall AlleDateien3Click(TObject *Sender);
        void __fastcall Dokumente3Click(TObject *Sender);
        void __fastcall Grafiken3Click(TObject *Sender);
        void __fastcall Andere3Click(TObject *Sender);
        void __fastcall StandardDokument3Click(TObject *Sender);
        void __fastcall AddLangNewDocLeer31Click(TObject *Sender);
        void __fastcall AddLangNewDocLeer32Click(TObject *Sender);
        void __fastcall AddLangNewDocLeer33Click(TObject *Sender);
        void __fastcall Neu4Click(TObject *Sender);
        void __fastcall DirektFTPExplorerDblClick(TObject *Sender);
        void __fastcall ToolButton33Click(TObject *Sender);
        void __fastcall DirektFTPExplorerEdited(TObject *Sender,
          TListItem *Item, AnsiString &S);
        void __fastcall QuickstartMenuPopup(TObject *Sender);
        void __fastcall QuickstartApp1Click(TObject *Sender);
        void __fastcall QuickstartApp2Click(TObject *Sender);
        void __fastcall QuickstartApp3Click(TObject *Sender);
        void __fastcall QuickstartApp4Click(TObject *Sender);
        void __fastcall QuickstartApp5Click(TObject *Sender);
        void __fastcall NeueVerknpfung1Click(TObject *Sender);
        void __fastcall DirektFTPListeEdited(TObject *Sender,
          TListItem *Item, AnsiString &S);
        void __fastcall WebBrowserProgressChange(TObject *Sender, long Progress, long ProgressMax);
        void __fastcall WebBrowserDocumentComplete(TObject *Sender, LPDISPATCH pDisp, TVariant* URL);
        void __fastcall FormatMenuPopup(TObject *Sender);
        void __fastcall EinfgenMenuPopup(TObject *Sender);
        void __fastcall Schrift1Click(TObject *Sender);
        void __fastcall Fett1Click(TObject *Sender);
        void __fastcall Kursiv1Click(TObject *Sender);
        void __fastcall Hochgestellt1Click(TObject *Sender);
        void __fastcall Tiefgestellt1Click(TObject *Sender);
        void __fastcall Prformatiert1Click(TObject *Sender);
        void __fastcall Code1Click(TObject *Sender);
        void __fastcall Emphatisch1Click(TObject *Sender);
        void __fastcall Zitat1Click(TObject *Sender);
        void __fastcall Adresse1Click(TObject *Sender);
        void __fastcall Gro1Click(TObject *Sender);
        void __fastcall Klein1Click(TObject *Sender);
        void __fastcall Gre11Click(TObject *Sender);
        void __fastcall Gre21Click(TObject *Sender);
        void __fastcall Gre31Click(TObject *Sender);
        void __fastcall Gre41Click(TObject *Sender);
        void __fastcall Gre51Click(TObject *Sender);
        void __fastcall Gre61Click(TObject *Sender);
        void __fastcall Listeneintrag1Click(TObject *Sender);
        void __fastcall Definitionsliste1Click(TObject *Sender);
        void __fastcall Definitionsabschnitt1Click(TObject *Sender);
        void __fastcall Definitionseintrag1Click(TObject *Sender);
        void __fastcall Abschnitt1Click(TObject *Sender);
        void __fastcall Hyperlink1Click(TObject *Sender);
        void __fastcall eMailVerweis1Click(TObject *Sender);
        void __fastcall Grafik1Click(TObject *Sender);
        void __fastcall Metatag1Click(TObject *Sender);
        void __fastcall httpscribede1Click(TObject *Sender);
        void __fastcall Plugins1Click(TObject *Sender);
        void __fastcall Buttonx1Click(TObject *Sender);
        void __fastcall ButtonxControlChange(TObject *Sender);
        void __fastcall TabellenAssistent1Click(TObject *Sender);
        void __fastcall MultimediaObjekt1Click(TObject *Sender);
        void __fastcall Trennlinie1Click(TObject *Sender);
        void __fastcall Anker1Click(TObject *Sender);
        void __fastcall Tabelle2Click(TObject *Sender);
        void __fastcall Zeile1Click(TObject *Sender);
        void __fastcall Kopfzelle1Click(TObject *Sender);
        void __fastcall Zelle1Click(TObject *Sender);
        void __fastcall berUnterschrift1Click(TObject *Sender);
        void __fastcall Formular2Click(TObject *Sender);
        void __fastcall Eingabefeld1Click(TObject *Sender);
        void __fastcall Textfeld1Click(TObject *Sender);
        void __fastcall AbsendenundZurcksetzenbutton1Click(
          TObject *Sender);
        void __fastcall Passwortfeld1Click(TObject *Sender);
        void __fastcall VerstecktesFeld1Click(TObject *Sender);
        void __fastcall Checkbox1Click(TObject *Sender);
        void __fastcall Radiobutton1Click(TObject *Sender);
        void __fastcall Auswahlliste1Click(TObject *Sender);
        void __fastcall Auswahleintrag1Click(TObject *Sender);
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall FramesAssistent1Click(TObject *Sender);
        void __fastcall FrameBereich1Click(TObject *Sender);
        void __fastcall Frame1Click(TObject *Sender);
        void __fastcall EingebettetesFrame1Click(TObject *Sender);
        void __fastcall StyleSheetDefinition1Click(TObject *Sender);
        void __fastcall StyleSheetZuweisungen1Click(TObject *Sender);
        void __fastcall ExterneStyleSheetDatei1Click(TObject *Sender);
        void __fastcall JavaScriptVorlagen1Click(TObject *Sender);
        void __fastcall JavaScript2Click(TObject *Sender);
        void __fastcall IncludeDatei1Click(TObject *Sender);
        void __fastcall ToolsMenuPopup(TObject *Sender);
        void __fastcall Schnellformatierung1Click(TObject *Sender);
        void __fastcall Paragraph1Click(TObject *Sender);
        void __fastcall Liste1Click(TObject *Sender);
        void __fastcall ExterneJavaScriptDatei1Click(TObject *Sender);
        void __fastcall ProjektBackup1Click(TObject *Sender);
        void __fastcall GrafikKatalog1Click(TObject *Sender);
        void __fastcall ThumbnailGenerator1Click(TObject *Sender);
        void __fastcall StatusLeisteClick(TObject *Sender);
        void __fastcall StyleSheetEditor1Click(TObject *Sender);
        void __fastcall XHTMLKonverter1Click(TObject *Sender);
        void __fastcall Includesaktualisieren1Click(TObject *Sender);
        void __fastcall Linkberprfung1Click(TObject *Sender);
        void __fastcall FormResize(TObject *Sender);
        void __fastcall MenuItem23Click(TObject *Sender);
        void __fastcall LeerzeichenShortCutExecute(TObject *Sender);
        void __fastcall ZeilenumbruchShortCut2Execute(TObject *Sender);
        void __fastcall KlammerAufShortCutExecute(TObject *Sender);
        void __fastcall KlammerZuShortCutExecute(TObject *Sender);
        void __fastcall AnfuehrungszeichenShortCutExecute(TObject *Sender);
        void __fastcall DateimanagerListeSelectItem(TObject *Sender,
          TListItem *Item, bool Selected);
        void __fastcall ProjekteListeSelectItem(TObject *Sender,
          TListItem *Item, bool Selected);
        void __fastcall FastCode1Click(TObject *Sender);
        void __fastcall ToolButton35MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton37MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton38MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton40MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton41MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton42MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton43MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton44MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton46MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton47MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton48MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton49MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton93Click(TObject *Sender);
        void __fastcall ToolButton94MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton95MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton96MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton98MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton99Click(TObject *Sender);
        void __fastcall ToolButton101Click(TObject *Sender);
        void __fastcall ToolButton59MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton60MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton62MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton63MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton65MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton66MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton67MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton77MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton53MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton54MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton55MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton56MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton58MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton78MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton80MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton81MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton82MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton83MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton84MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton86MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton87MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton89MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton90MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall ToolButton92MouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall Downloadzeit1Click(TObject *Sender);
        void __fastcall Optionen1Click(TObject *Sender);
        void __fastcall DateimanagerListeKeyPress(TObject *Sender,
          char &Key);
        void __fastcall ProjekteListeKeyPress(TObject *Sender, char &Key);
        void __fastcall DirektFTPListeKeyPress(TObject *Sender, char &Key);
        void __fastcall Hilfethemen1Click(TObject *Sender);
        void __fastcall Editor1Click(TObject *Sender);
        void __fastcall XHTML1Click(TObject *Sender);
        void __fastcall BinrModus1Click(TObject *Sender);
        void __fastcall AsciiModus1Click(TObject *Sender);
        void __fastcall BinrModus2Click(TObject *Sender);
        void __fastcall AsciiModus2Click(TObject *Sender);
        void __fastcall ParagraphShortCutExecute(TObject *Sender);
        void __fastcall Eigenschaften3Click(TObject *Sender);
        void __fastcall ToolButton102Click(TObject *Sender);
        void __fastcall FarbPaletteShapeMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall FarbCursorShapeMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall PassendeKlammerfinden1Click(TObject *Sender);
private:	// Anwenderdeklarationen
public:		// Anwenderdeklarationen
        __fastcall THauptformular(TComponent* Owner);
        bool first_date;
        int editor_language;
        bool editor_file_at_start;
        bool editor_show_tip;
        bool editor_xhtml_mode;
        bool editor_events_tab;
        String editor_font_face;
        int editor_font_size;
        String editor_word_delimiters;
        TColor editor_background_color;
        String includes_dir;
        int file_counter;
        int max_history_entries;
        String program_dir;
        String program_version;
        String project_dir;
        String fileexplorer_dir;
        String projectexplorer_dir;
        bool msie_installed;
        TWebBrowser *msie_helpbrowser;
        TWebBrowser *msie_previewbrowser;
        String addlang_current_tag;
        String addlang_extensions_all;
        int addlang_langs_count;
        String documents_name;
        String documents_extension;
        String browser_path_1;
        String browser_desc_1;
        String browser_path_2;
        String browser_desc_2;
        String browser_path_3;
        String browser_desc_3;
        bool browser_confirm_save;
        String standard_xhtml_documentation;
        String docfile_extensions;
        String graphicfile_extensions;
        String multimediafile_extensions;
        String cssfile_extensions;
        String javascriptfile_extensions;
        String graphics_viewer_file;
        String standard_graphic_tool;
        String standard_template;
        String color_palette;
        bool use_ascii_code;
        bool use_color_names;
        bool plugin_read_name_title;
        bool textarea_read_xhtml_title;
        bool textarea_save_files_in_unix;
        bool textarea_print_plaintext;
        int  textarea_tabstops;
        bool textarea_wordwrap;
        bool textarea_linenumbers;
        bool textarea_convert_special_chars;
        String help_align;
        int help_size;
        bool help_dock_window;
        int help_window_top;
        int help_window_left;
        int help_window_height;
        int help_window_width;
        String directftp_current_profile;
        String directftp_current_dir;
        int directftp_file_size;
        bool directftp_connect_at_start;
        bool directftp_show_menue;
        String directftp_temp_input;
        bool directftp_check_connection;
        String quickstart_path_1;
        String quickstart_desc_1;
        String quickstart_para_1;
        String quickstart_path_2;
        String quickstart_desc_2;
        String quickstart_para_2;
        String quickstart_path_3;
        String quickstart_desc_3;
        String quickstart_para_3;
        String quickstart_path_4;
        String quickstart_desc_4;
        String quickstart_para_4;
        String quickstart_path_5;
        String quickstart_desc_5;
        String quickstart_para_5;
        bool tag_php_compatible;
        bool tag_currently_editing;
        bool tag_automatic_position;
        bool tag_auto_complete;
        String tag_current;
        int tag_sel_position;
        bool localhost_use;
        String localhost_adress;
        String image_catalog_file;
        bool use_topstyle;
        String css_openfile;
        String css_editstyle;
        String css_editstyleblock;
        bool css_edit_editstyle;
        bool css_edit_editstyleblock;
        TColor syntax_color_tags;
        TColor syntax_color_attributes;
        TColor syntax_color_links;
        TColor syntax_color_linkattrs;
        TColor syntax_color_comments;
        TColor syntax_color_styles;
        TColor syntax_color_styleattrs;
        TColor syntax_color_stylecomments;
        TColor syntax_color_javascript;
        TColor syntax_color_tables;
        TColor syntax_color_tableattrs;
        TColor syntax_color_specialchars;
        TColor syntax_color_php_area;
        TColor syntax_color_php_comments;
        TColor syntax_color_php_keywords;
        TColor syntax_color_php_attrs;
        TColor syntax_color_sql_functions;
        TColor syntax_color_css_comments;
        TColor syntax_color_css_strings;
        TColor syntax_color_css_chars;
        TColor syntax_color_css_tags;
        TColor syntax_color_css_attrs;
        bool syntax_bold_tags;
        bool syntax_bold_attributes;
        bool syntax_bold_links;
        bool syntax_bold_linkattrs;
        bool syntax_bold_comments;
        bool syntax_bold_styles;
        bool syntax_bold_styleattrs;
        bool syntax_bold_stylecomments;
        bool syntax_bold_javascript;
        bool syntax_bold_tables;
        bool syntax_bold_tableattrs;
        bool syntax_bold_specialchars;
        bool syntax_bold_php_area;
        bool syntax_bold_php_comments;
        bool syntax_bold_php_keywords;
        bool syntax_bold_php_attrs;
        bool syntax_bold_sql_functions;
        bool syntax_bold_css_comments;
        bool syntax_bold_css_strings;
        bool syntax_bold_css_chars;
        bool syntax_bold_css_tags;
        bool syntax_bold_css_attrs;
        bool syntax_italic_tags;
        bool syntax_italic_attributes;
        bool syntax_italic_links;
        bool syntax_italic_linkattrs;
        bool syntax_italic_comments;
        bool syntax_italic_styles;
        bool syntax_italic_styleattrs;
        bool syntax_italic_stylecomments;
        bool syntax_italic_javascript;
        bool syntax_italic_tables;
        bool syntax_italic_tableattrs;
        bool syntax_italic_specialchars;
        bool syntax_italic_php_area;
        bool syntax_italic_php_comments;
        bool syntax_italic_php_keywords;
        bool syntax_italic_php_attrs;
        bool syntax_italic_sql_functions;
        bool syntax_italic_css_comments;
        bool syntax_italic_css_strings;
        bool syntax_italic_css_chars;
        bool syntax_italic_css_tags;
        bool syntax_italic_css_attrs;
        void __fastcall AddLangPrepareSystem();
        void __fastcall AddLangCreateMenu(TObject *Sender);
        void __fastcall AddLangMenuClick(TObject *Sender);
        bool __fastcall AddLangFile(String);
        void __fastcall ScribePluginEngine(String);
        String __fastcall ParseString (String, String, int);
        TForm* __fastcall CreateChildForm(String, String, String);
        String __fastcall SearchXHTMLTitle(TStrings *HTMLTitleDatei);
        String __fastcall ReplaceString(String, String, String, bool, bool);
        String __fastcall BuildFilter(String);
        TStrings* __fastcall HistoryRead(String);
        void __fastcall HistoryWrite(String, TStrings* HistoryItems);
        bool __fastcall FTPFile(String);
        bool __fastcall DocumentFile(String);
        bool __fastcall CSSFile(String);
        bool __fastcall GraphicFile(String);
        bool __fastcall MultimediaFile(String);
        bool __fastcall JavaScriptFile(String);
        bool __fastcall ProjectsLoad(String);
        void __fastcall ProjectsLoadFolders(String);
        void __fastcall FileFillList(TLsFilelistView28 *FillListSource, TListView *FillListTarget);
        bool __fastcall FileSave(TPlusMemo *PlusMemoFileSave, String, bool);
        void __fastcall FileExecute(String, String);
        int __fastcall  FileGetSize(String);
        void __fastcall FileAppendToFileList(String);
        int __fastcall  FileCalculateIcon(String);
        void __fastcall FileAppendToRecent(String);
        void __fastcall FileCopy(TListBox *FileCopySource, String);
        bool __fastcall FileCopyOnlyOne(String, String);
        void __fastcall FileDelete(TListBox *FileDeleteSource, bool);
        bool __fastcall FileDeleteOnlyOne(String, bool);
        bool __fastcall FileRename(String, String);
        bool __fastcall FileAskSave(TPlusMemo *PlusMemoFileAskSave, String);
        void __fastcall DirectoryFindSubs(String, TListBox *DirectorySubsListe);
        bool __fastcall DirectoryDelete(String);
        String __fastcall DirectorySameAndRelative(String);
        bool __fastcall DirectorySame(String);
        String __fastcall DirectoryRelativePath(String);
        String __fastcall DirectoryWrongPath(String);
        void __fastcall ButtonsEnable();
        void __fastcall ButtonsDisable();
        void __fastcall CSSEditorFileOpen(String);
        String __fastcall CSSEditorEditStyle(String);
        String __fastcall CSSEditorEditStyleBlock(String);
        String __fastcall ColorColorToXHTMLCode(TColor);
        TColor __fastcall ColorXHTMLCodeToColor(String);
        TColor __fastcall ColorWindowsDialogShow(TColor);
        void __fastcall ColorButton(TSpeedButton *ColorButton, TColor);
        void __fastcall ColorAssignColorToButton(TSpeedButton *ColorAssignButton, TColor, TColorDialog *ColorAssignDialog);
        void __fastcall ColorSetUserDefined(TColorDialog *ColorSetDialog);
        void __fastcall ColorReadUserDefined(TColorDialog *ColorReadDialog);
        void __fastcall HelpShow(TForm *SubmittedHelpForm, String, bool);
        void __fastcall HelpKeywordShow(String);
        void __fastcall InternalBrowserShow(String);
        void __fastcall BrowserShow(int, String);
        void __fastcall DirectFTPLoadProfiles(String);
        String __fastcall DirectFTPURLCompatible(String);
        String __fastcall DirectFTPURLDecompatible(String);
        bool __fastcall DirectFTPCheckConnection();
        String __fastcall Base64Decode(String);
        String __fastcall Base64Encode(String);
        String __fastcall ConvertDateToDatum(String);
        void __fastcall TagInsert(String, String);
        void __fastcall TagInsertAndFindPosition(String, String, String, String);
        bool __fastcall TagInIt();
        void __fastcall TagAppendAttribute(String);
        String __fastcall TagCurrent();
        String __fastcall TagNormalize(String, bool);
        bool __fastcall TagAttributeContainsStandalone(String, String);
        int __fastcall TagAttributeGetNumeric(String, String);
        String __fastcall TagAttributeGetString(String, String);
        TColor __fastcall TagAttributeGetColor(String, String);
        int __fastcall TagAttributeGetPercent(String, String);
        bool __fastcall TagAttributeContainsPercent(String, String);
        bool __fastcall TagAttributeContainsAttribute(String, String);
        String __fastcall TagAttributeRemoveMainTag(String, String);
        String __fastcall TagAttributeRemoveAttribute(String, String);
        String __fastcall TagAttributeRemoveStandalone(String, String);
        void __fastcall ButtonxListItems();
        String __fastcall ButtonxEngine(String);
        String __fastcall ImageCatalogShow();
        String __fastcall XHTMLBracketAdd(String);
        String __fastcall QuotesDelete(String);
};
//---------------------------------------------------------------------------
extern PACKAGE THauptformular *Hauptformular;
//---------------------------------------------------------------------------
#endif
